name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-debian:
    runs-on: ubuntu-latest

    steps:
      - name: Update apt db
        run: sudo apt update

      - name: Install Packagers & Cross-Compiler
        run: sudo apt install -y devscripts debhelper gcc-aarch64-linux-gnu

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Make Debian Package
        run: make package-debian

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: debpkg
          path: out/debian/*

  build-tarball:
    runs-on: ubuntu-latest

    steps:
      - name: Update apt db
        run: sudo apt update

      - name: Install Cross-Compiler
        run: sudo apt install -y gcc-aarch64-linux-gnu

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & Make Tarball
        run: make package-tar

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: tar
          path: out/tar/*

  build-arch:
    runs-on: ubuntu-latest
    container:
      image: cerebrate/fuckarch:right-in-the-ear

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Permissions fixup
        run: sudo chown -R build .

      - name: Build Package
        run: sudo -u build make package-arch

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: zst
          path: out/arch/*
